/* ============================================================================
   GLOWENVY — PRODUCT CATALOG
   ============================================================================
   Generated by admin.html on 2026-08-15.
   This is plain text — open it in any text editor, or keep using admin.html
   to manage it with point-and-click forms.

   HOW TO ADD A PRODUCT BY HAND (optional — admin.html does this for you):
   Copy a product block below (from { to },), paste it above the closing
   "];", and fill in your own details. "id" can be left out for new hand-
   added entries — one will be assigned automatically when the page loads.

   FIELD NOTES:
   - description: one short paragraph.
   - benefits: put each benefit on its own line — it's shown as a bullet list.
   - ingredients: put each key ingredient on its own line (name first, then
     what it does) — also shown as a bullet list.
   - caution: one short paragraph of warnings / who should avoid it.
   - howToUse: one short paragraph.
   - skinTypes: which of SKIN_TYPES (below) the product suits — this also
     powers the "Suitable For" tags shown on the product.
   ============================================================================ */

// The shop's category tabs/filters, in the order they should appear.
const CATEGORIES = ["Face Care","Body Care","Sun Protection","Supplements","Glow Envy Sets","Bundles"];

// The skin-type filter options. Products reference these in their "skinTypes" list.
const SKIN_TYPES = ["oily","dry","combination","sensitive"];

const PRODUCTS = [
  {
    id: 4,
    name: "Niacinamide SPF 50 Fluid",
    category: "Sun Protection",
    price: 12500,
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&q=80&auto=format&fit=crop",
    description: "A broad-spectrum SPF 50 fluid boosted with niacinamide, formulated to sit invisibly on deeper skin tones with no white cast, no greasy finish and no pilling under makeup.",
    benefits: "Broad-spectrum protection against UVA and UVB rays\nLeaves no white cast on deeper skin tones\nLightweight, matte-adjacent finish that wears well under makeup\nNiacinamide supports tone and a healthy-looking barrier alongside sun protection",
    ingredients: "Niacinamide – supports even tone and a healthy skin barrier\nZinc PCA – helps manage shine throughout the day\nPanthenol – soothes skin that can feel sensitised by sun exposure\nBroad-spectrum UV filters – protect against UVA and UVB rays (SPF 50)",
    caution: "For external use only; avoid contact with eyes. Sunscreen alone should not be relied on for full sun protection — combine with shade, protective clothing and avoiding peak sun hours. Discontinue if irritation occurs. Store below 30°C, away from direct sunlight.",
    howToUse: "Apply generously as the final step of your morning routine, at least 15 minutes before sun exposure. Reapply every 2 hours if outdoors, swimming or sweating.",
    skinTypes: ["oily","combination"],
    bestseller: true,
    isNew: false,
    rating: 4.8,
    reviews: 745
  },
  {
    id: 6,
    name: "Snow White Luxury Body Oil",
    category: "Body Care",
    price: 13500,
    image: "https://res.cloudinary.com/dvojnfcts/image/upload/v1784036032/Untitled_design_cio3ll.jpg",
    description: "Experience radiant, healthy-looking skin with our Snow White Luxury Body Oil. This highly concentrated body oil is expertly formulated to help brighten the appearance of dull skin, improve the look of uneven skin tone, and leave your skin with a smooth, luminous glow. Its lightweight, nourishing formula absorbs easily without feeling greasy, making it ideal for daily use.",
    benefits: "* Helps brighten the appearance of the skin.\n* Promotes a radiant, healthy glow.\n* Helps improve the appearance of dark spots and uneven skin tone.\n* Nourishes and softens the skin.\n* Lightweight, non-greasy finish.\n* Suitable for daily use.",
    ingredients: "* Sweet Almond Oil – Deeply moisturizes, softens, and nourishes the skin.\n* Kojic Acid – Helps improve the appearance of uneven skin tone and dark spots.\n* Glutathione – Supports a brighter, more radiant-looking complexion.",
    caution: "* Dull-looking skin\n* Uneven skin tone\n* Skin with the appearance of dark spots\n* Anyone seeking a brighter, radiant glow",
    howToUse: "After cleansing, dispense a small amount into the palm of your hand and massage evenly over your body until fully absorbed. For best results, use morning and night and follow with sunscreen during the day to help protect your skin from UV exposure.",
    skinTypes: ["combination"],
    bestseller: true,
    isNew: false,
    rating: 4.8,
    reviews: 25
  },
  {
    id: 7,
    name: "Lightening Glow Bar Soap",
    category: "Body Care",
    price: 5000,
    image: "https://res.cloudinary.com/ny0or3ln/image/upload/v1785099694/b8082d22-e903-49a5-9a90-dd601f9e54c3_ktg4dk.jpg",
    description: "Reveal smoother, brighter, and healthier-looking skin with Glow Envy by Ivy Lightening Glow Bar Soap. This nourishing body and face soap is specially formulated to deeply cleanse, gently exfoliate, and promote a naturally radiant complexion.\n\nIt helps remove dirt, excess oil, and dead skin cells while improving the appearance of uneven skin tone, leaving your skin feeling clean, refreshed, and silky smooth after every wash.\n\nSuitable for daily use and designed for all skin types, this bar soap is the perfect addition to your skincare routine for a healthy, glowing look.",
    benefits: "Gently exfoliates dead skin cells\n\t•\tDeeply cleanses the skin\n\t•\tPromotes a brighter, more even-looking complexion\n\t•\tHelps improve the appearance of dark spots\n\t•\tLeaves the skin soft, smooth, and refreshed\n\t•\tSuitable for both face and body\n\t•\tSuitable for all skin types",
    ingredients: "•\tKojic Acid\n\t•\tTurmeric Extract\n\t•\tVitamin E\n\t•\tGlycerin\n\t•\tNatural Botanical Extracts",
    caution: "•\tFor external use only.\n\t•\tAvoid contact with the eyes.\n\t•\tPerform a patch test before first use.\n\t•\tDiscontinue use if irritation occurs.\n\t•\tStore in a cool, dry place.",
    howToUse: "1.\tWet your skin with clean water.\n\t2.\tLather the soap in your hands or on a sponge.\n\t3.\tGently massage onto your face and body using circular motions.\n\t4.\tLeave on for 1–2 minutes, then rinse thoroughly with water.\n\t5.\tFollow with your moisturizer or body lotion. During the day, apply sunscreen to protect your skin",
    skinTypes: [],
    bestseller: false,
    isNew: true,
    rating: 4.5,
    reviews: 25
  },
  {
    id: 8,
    name: "Snow White Luxury Body Oil",
    category: "Glow Envy Sets",
    price: 13500,
    image: "https://res.cloudinary.com/ny0or3ln/image/upload/v1785099694/f305f4ec-59e1-4a27-9f7b-470f33602245_ksklzi.jpg",
    description: "Experience radiant, healthy-looking skin with our Snow White Luxury Body Oil. This highly concentrated body oil is expertly formulated to help brighten the appearance of dull skin, improve the look of uneven skin tone, and leave your skin with a smooth, luminous glow. Its lightweight, nourishing formula absorbs easily without feeling greasy, making it ideal for daily use.",
    benefits: "Helps brighten the appearance of the skin.\nPromotes a radiant, healthy glow.\nHelps improve the appearance of dark spots and uneven skin tone.\nNourishes and softens the skin.\nLightweight, non-greasy finish.\nSuitable for daily use.",
    ingredients: "* Sweet Almond Oil – Deeply moisturizes, softens, and nourishes the skin.\n* Kojic Acid – Helps improve the appearance of uneven skin tone and dark spots.\n* Glutathione – Supports a brighter, more radiant-looking complexion.",
    caution: "",
    howToUse: "After cleansing, dispense a small amount into the palm of your hand and massage evenly over your body until fully absorbed. For best results, use morning and night and follow with sunscreen during the day to help protect your skin from UV exposure.",
    skinTypes: [],
    bestseller: false,
    isNew: true,
    rating: 4.5,
    reviews: 25
  },
  {
    id: 9,
    name: "Pink Lips Combo",
    category: "Bundles",
    price: 5000,
    image: "https://res.cloudinary.com/ny0or3ln/image/upload/v1785099694/e7624e60-4a33-440c-a9b0-bc7ea65deec9_to4io7.jpg",
    description: "Get soft, smooth, and healthy-looking lips with the Glow Envy by Ivy Pink Lips Combo. This nourishing lip care duo combines a gentle Lip Scrub and a moisturizing Pink Lips Balm to help exfoliate dry, flaky lips while keeping them soft, hydrated, and naturally radiant.\n\nThe lip scrub buffs away dead skin cells, allowing the lip balm to lock in moisture for a smoother, plumper-looking pout. Perfect for daily lip maintenance and before applying lipstick or lip gloss.",
    benefits: "•\tGently exfoliates dry, flaky lips\n\t•\tMoisturizes and nourishes the lips\n\t•\tLeaves lips soft, smooth, and supple\n\t•\tHelps improve the appearance of dull lips\n\t•\tPrepares lips for flawless lipstick application\n\t•\tSuitable for everyday use",
    ingredients: "•\t💖 Glow Envy by Ivy Lip Scrub\n\t•\t💖 Glow Envy by Ivy Pink Lips Balm",
    caution: "",
    howToUse: "Step 1: Apply a small amount of the Lip Scrub to clean lips and gently massage in circular motions for 30–60 seconds. Wipe off or rinse gently.\n\nStep 2: Apply the Pink Lips Balm generously to moisturize and protect your lips.\n\nFor best results, use the lip scrub 2–3 times weekly and the lip balm daily or whenever your lips feel dry.",
    skinTypes: ["dry"],
    bestseller: false,
    isNew: true,
    rating: 4.5,
    reviews: 25
  },
  {
    id: 10,
    name: "901451",
    category: "Bundles",
    price: 80000,
    image: "https://res.cloudinary.com/ny0or3ln/image/upload/v1785099693/a41079e9-19fa-4f04-8b99-59887ccf9110_q6hfr7.jpg",
    description: "",
    benefits: "",
    ingredients: "",
    caution: "",
    howToUse: "",
    skinTypes: [],
    bestseller: false,
    isNew: true,
    rating: 4.5,
    reviews: 25
  },
  {
    id: 11,
    name: "258815",
    category: "Bundles",
    price: 80000,
    image: "https://res.cloudinary.com/ny0or3ln/image/upload/v1785099693/1117740d-9e83-4de2-a89a-5dbaeac406f3_jg2xga.jpg",
    description: "",
    benefits: "",
    ingredients: "",
    caution: "",
    howToUse: "",
    skinTypes: [],
    bestseller: false,
    isNew: true,
    rating: 4.5,
    reviews: 25
  },
  {
    id: 12,
    name: "892179",
    category: "Bundles",
    price: 80000,
    image: "https://res.cloudinary.com/ny0or3ln/image/upload/v1785099693/3308a446-c840-41c9-9389-974a217ba987_kxfqnl.jpg",
    description: "",
    benefits: "",
    ingredients: "",
    caution: "",
    howToUse: "",
    skinTypes: [],
    bestseller: false,
    isNew: true,
    rating: 4.5,
    reviews: 25
  },
  {
    id: 13,
    name: "382071",
    category: "Bundles",
    price: 80000,
    image: "https://res.cloudinary.com/ny0or3ln/image/upload/v1785099693/406892e9-82d6-480b-bcbe-a5b7f162132f_gsqpaw.jpg",
    description: "",
    benefits: "",
    ingredients: "",
    caution: "",
    howToUse: "",
    skinTypes: [],
    bestseller: false,
    isNew: true,
    rating: 4.5,
    reviews: 25
  },
  {
    id: 14,
    name: "529116",
    category: "Bundles",
    price: 80000,
    image: "https://res.cloudinary.com/ny0or3ln/image/upload/v1785099693/5510972b-926a-4bfa-9749-8186fc69ad86_ubckj2.jpg",
    description: "",
    benefits: "",
    ingredients: "",
    caution: "",
    howToUse: "",
    skinTypes: [],
    bestseller: false,
    isNew: true,
    rating: 4.5,
    reviews: 25
  },
  {
    id: 15,
    name: "893202",
    category: "Bundles",
    price: 80000,
    image: "https://res.cloudinary.com/ny0or3ln/image/upload/v1785099693/81403b0a-9d73-4d0b-a466-c1e2a5f7f7bd_bppanw.jpg",
    description: "",
    benefits: "",
    ingredients: "",
    caution: "",
    howToUse: "",
    skinTypes: [],
    bestseller: false,
    isNew: true,
    rating: 4.5,
    reviews: 25
  },
  {
    id: 16,
    name: "719771",
    category: "Bundles",
    price: 80000,
    image: "https://res.cloudinary.com/ny0or3ln/image/upload/v1785099692/412ded45-e896-4790-8715-9f170151b085_htqfff.jpg",
    description: "",
    benefits: "",
    ingredients: "",
    caution: "",
    howToUse: "",
    skinTypes: [],
    bestseller: false,
    isNew: true,
    rating: 4.5,
    reviews: 25
  },
  {
    id: 17,
    name: "Extreme Radiance Soap",
    category: "Body Care",
    price: 8000,
    image: "https://res.cloudinary.com/ny0or3ln/image/upload/v1785099692/6f69f9b3-37e5-48e6-91d3-77a896665b65_qdfmcd.jpg",
    description: "Reveal smoother, brighter, and healthier-looking skin with Extreme Radiance Soap, a luxurious exfoliating body and face soap carefully formulated for all skin types.\n\nThis multi-benefit cleansing soap helps remove dead skin cells, deeply cleanse pores, and promote a more even-looking complexion without leaving your skin feeling stripped. With regular use, your skin feels softer, looks more radiant, and develops a healthy glow.\n\nWhether you’re dealing with dull skin, uneven skin tone, or rough texture, Extreme Radiance Soap is designed to support a smoother, refreshed appearance as part of your daily skincare routine.",
    benefits: "* Gently exfoliates dead skin cells\n* Deeply cleanses dirt, oil, and impurities\n* Promotes a brighter, more even-looking complexion\n* Helps improve the appearance of dark spots and uneven skin tone\n* Leaves skin feeling soft, smooth, and refreshed\n* Suitable for both the face and body\n* Suitable for all skin types",
    ingredients: "* Kojic Acid\n* Turmeric Extract\n* Licorice Extract\n* Glycerin\n* Vitamin E\n* Plant-Based Cleansing Agents",
    caution: "* For external use only.\n* Avoid contact with the eyes.\n* Discontinue use if irritation occurs.\n* Perform a patch test before first use.\n* Keep out of reach of children.",
    howToUse: "1. Wet your skin with clean water.\n2. Lather the soap in your hands or on a sponge.\n3. Gently massage onto the face and body using circular motions.\n4. Leave on for 1–3 minutes if your skin tolerates it.\n5. Rinse thoroughly with clean water.\n6. Follow with your toner (if used), serum, moisturizer, or body lotion, and apply sunscreen during the day.\n\nFor best results, use once or twice daily as directed by your skincare routine.",
    skinTypes: ["combination"],
    bestseller: false,
    isNew: true,
    rating: 4.5,
    reviews: 25
  },
  {
    id: 18,
    name: "646704",
    category: "Bundles",
    price: 80000,
    image: "https://res.cloudinary.com/ny0or3ln/image/upload/v1785099692/44a881c4-8fb0-44d5-a51b-cb2ab8d129b0_h5fvt9.jpg",
    description: "",
    benefits: "",
    ingredients: "",
    caution: "",
    howToUse: "",
    skinTypes: [],
    bestseller: false,
    isNew: true,
    rating: 4.5,
    reviews: 25
  },
  {
    id: 19,
    name: "895029",
    category: "Bundles",
    price: 80000,
    image: "https://res.cloudinary.com/ny0or3ln/image/upload/v1785099692/8d5fcda6-8e48-427c-ad07-47558b8d37fa_dacnmy.jpg",
    description: "",
    benefits: "",
    ingredients: "",
    caution: "",
    howToUse: "",
    skinTypes: [],
    bestseller: false,
    isNew: true,
    rating: 4.5,
    reviews: 25
  },
  {
    id: 20,
    name: "106722",
    category: "Bundles",
    price: 80000,
    image: "https://res.cloudinary.com/ny0or3ln/image/upload/v1785099692/9e2405e7-4cff-4202-864f-75b4a9e0106e_hw0s03.jpg",
    description: "",
    benefits: "",
    ingredients: "",
    caution: "",
    howToUse: "",
    skinTypes: [],
    bestseller: false,
    isNew: true,
    rating: 4.5,
    reviews: 25
  },
  {
    id: 21,
    name: "885206",
    category: "Bundles",
    price: 80000,
    image: "https://res.cloudinary.com/ny0or3ln/image/upload/v1785099692/4d666628-c2f9-4eaa-9269-e6b66aa7ed66_vjyr2t.jpg",
    description: "",
    benefits: "",
    ingredients: "",
    caution: "",
    howToUse: "",
    skinTypes: [],
    bestseller: false,
    isNew: true,
    rating: 4.5,
    reviews: 25
  }
];
